# Generated by Django 3.0.1 on 2020-03-15 09:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserProfilePictureUrl', models.ImageField(blank=True, default='DefaultProfileImage.png', upload_to='UserProfilePicture/%Y/%m/%d')),
                ('UserMobileNumber', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Must be in length of 10', regex='^\\d{10}$')])),
                ('UserAltMobileNumber', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Must be in length of 10', regex='^\\d{10}$')])),
                ('UserCompanyName', models.CharField(max_length=50)),
                ('UserCompanyYear', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Must be in length of 4 and all digits', regex='^\\d{4}$')])),
                ('UserAccountStatus', models.CharField(choices=[('Active', 'Active'), ('DeActivated', 'DeActivated')], default='Active', max_length=20)),
                ('UserAlertStatus', models.CharField(choices=[('On', 'On'), ('Off', 'Off')], default='Active', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SellerPromoterCEOName', models.CharField(max_length=30)),
                ('SellerFaxNumber', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Must be in length of 15', regex='^\\d{15}$')])),
                ('SellerAltFaxNumber', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Must be in length of 15', regex='^\\d{15}$')])),
                ('Profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accountsApp.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Statutory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StatutoryGSTIN', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Must be in length of 15', regex='^\\d{15}]$')])),
                ('StatutoryPanNumber', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Must be in length of 10', regex='^\\d{10}]$')])),
                ('StatutoryTanNumber', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Must be in length of 10', regex='^\\d{10}]$')])),
                ('StatutoryCinNumber', models.CharField(blank=True, max_length=21, validators=[django.core.validators.RegexValidator(message='Must be in length of 21', regex='^\\d{21}]$')])),
                ('StatutoryDgftNumber', models.CharField(blank=True, max_length=21, validators=[django.core.validators.RegexValidator(message='Must be in length of 6', regex='^\\d{15}]$')])),
                ('Seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accountsApp.Seller')),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BusinessCeoName', models.CharField(blank=True, max_length=30)),
                ('BusinessBusinessType', models.CharField(blank=True, max_length=30)),
                ('BusinessOwnershipType', models.CharField(blank=True, max_length=30)),
                ('BusinessNumberOfEmployee', models.CharField(blank=True, max_length=6, validators=[django.core.validators.RegexValidator(message='Must be in length of 6', regex='^\\d{6}$')])),
                ('BusinessAnnualTurnover', models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message='Must be in length of 10', regex='^\\d{10}$')])),
                ('BusinessCompanyLogo', models.ImageField(blank=True, default='DefaultCompanyLogoImage.png', upload_to='CompanyLogoPicture/%Y/%m/%d')),
                ('BusinessCompanyWebsite', models.CharField(blank=True, max_length=100)),
                ('BusinessCatalogUrl', models.CharField(blank=True, max_length=100)),
                ('BusinessCardFrontUrl', models.CharField(blank=True, max_length=100)),
                ('BusinessCardBackUrl', models.ImageField(blank=True, default='DefaultBusinessCardImage.png', upload_to='BusinessCardPicture/%Y/%m/%d')),
                ('Seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accountsApp.Seller')),
            ],
        ),
    ]
