# Generated by Django 3.0.1 on 2020-03-25 07:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='BusinessAnnualTurnover',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message='Must be in length of 10', regex='^\\d{0-10}$')]),
        ),
        migrations.AlterField(
            model_name='business',
            name='BusinessNumberOfEmployee',
            field=models.CharField(blank=True, max_length=6, validators=[django.core.validators.RegexValidator(message='Must be in length of 6', regex='^\\d{0-6}$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='UserCompanyYear',
            field=models.CharField(blank=True, max_length=4, validators=[django.core.validators.RegexValidator(message='Must be in length of 4 and all digits', regex='^\\d{4}$')]),
        ),
    ]
