# Generated by Django 3.0.1 on 2020-04-02 08:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsApp', '0002_auto_20200325_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='Profile',
        ),
        migrations.RemoveField(
            model_name='statutory',
            name='Seller',
        ),
        migrations.AlterField(
            model_name='profile',
            name='UserMobileNumber',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Must be in length of 10', regex='^\\d{10}$')]),
        ),
        migrations.DeleteModel(
            name='Business',
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
        migrations.DeleteModel(
            name='Statutory',
        ),
    ]
