# Generated by Django 3.0.1 on 2020-04-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerAccountApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='BusinessCardBackUrl',
            field=models.ImageField(blank=True, default='DefaultBusinessCardImage.png', unique=True, upload_to='BusinessCardBackPicture/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='business',
            name='BusinessCardFrontUrl',
            field=models.ImageField(blank=True, default='DefaultBusinessCardImage.png', unique=True, upload_to='BusinessCardFrontPicture/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='business',
            name='BusinessCatalogUrl',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
