# Generated by Django 3.0.1 on 2020-04-22 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellerAccountApp', '0002_auto_20200402_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SellerAddress', models.CharField(blank=True, max_length=100)),
                ('SellerAddressBlockNumber', models.CharField(blank=True, max_length=10)),
                ('SellerAddressStreet', models.CharField(blank=True, max_length=30)),
                ('SellerAddressLocality', models.CharField(blank=True, max_length=20)),
                ('SellerAddressLandMark', models.CharField(blank=True, max_length=20)),
                ('SellerAddressCity', models.CharField(blank=True, max_length=20)),
                ('SellerAddressPinCode', models.CharField(blank=True, max_length=20)),
                ('SellerAddressState', models.CharField(blank=True, max_length=20)),
                ('SellerAddressCountry', models.CharField(blank=True, default='India', max_length=20)),
                ('SellerAddressType', models.CharField(blank=True, max_length=20)),
                ('Seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sellerAccountApp.Seller')),
            ],
        ),
    ]
