# Generated by Django 3.0.1 on 2020-04-23 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellerAccountApp', '0004_auto_20200424_0339'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExportCategoryName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ImpCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImpCategoryName', models.CharField(max_length=50)),
                ('ExportCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productApp.ExportCategory')),
            ],
        ),
        migrations.CreateModel(
            name='IndustryCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IndustryCategoryName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=50)),
                ('ProductImageUrl', models.ImageField(blank=True, default='DefaultProductPicture.png', upload_to='ProductPicture/%Y/%m/%d')),
                ('ProductPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('ProductDescription', models.TextField(blank=True, max_length=150)),
                ('ProductMinimumOrderQuantity', models.DecimalField(blank=True, decimal_places=5, max_digits=10)),
                ('ProductProductionCapacity', models.CharField(blank=True, max_length=50)),
                ('ProductCode', models.CharField(blank=True, max_length=20)),
                ('ProductDeliveryTime', models.CharField(blank=True, max_length=20)),
                ('ProductPackagingDetails', models.CharField(blank=True, max_length=500)),
                ('ImpCategory', models.ManyToManyField(to='productApp.ImpCategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductCurrencyName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProductMeasuringUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductMeasuringUnitName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductSpecificationName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SpecificationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SpecificationTypeName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SpecificationValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SpecificationValueValue', models.CharField(max_length=50)),
                ('ProductSpecification_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productApp.ProductSpecification')),
                ('Product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productApp.Product')),
            ],
        ),
        migrations.AddField(
            model_name='productspecification',
            name='SpecificationType_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productApp.SpecificationType'),
        ),
        migrations.AddField(
            model_name='product',
            name='ProductCurrency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productApp.ProductCurrency'),
        ),
        migrations.AddField(
            model_name='product',
            name='ProductMeasuringUnit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productApp.ProductMeasuringUnit'),
        ),
        migrations.AddField(
            model_name='product',
            name='Seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellerAccountApp.Seller'),
        ),
        migrations.AddField(
            model_name='exportcategory',
            name='IndustryCategory',
            field=models.ManyToManyField(to='productApp.IndustryCategory'),
        ),
    ]
