# Generated by Django 3.0.1 on 2020-04-23 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0002_auto_20200424_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ProductImageUrl',
            field=models.ImageField(blank=True, null=True, upload_to='ProductPicture/%Y/%m/%d'),
        ),
    ]
